package com.example.playlistmakernewversion

data class Country(
    val alpha2: String,
    val alpha3: String,
    val name: String
)

val countries = listOf(
    Country("AD","AND","Andorra"),
    Country("AE","ARE","United Arab Emirates"),
    Country("AF","AFG","Afghanistan"),
    Country("AG","ATG","Antigua and Barbuda"),
    Country("AI","AIA","Anguilla"),
    Country("AL","ALB","Albania"),
    Country("AM","ARM","Armenia"),
    Country("AO","AGO","Angola"),
    Country("AR","ARG","Argentina"),
    Country("AT","AUT","Austria"),
    Country("AU","AUS","Australia"),
    Country("AZ","AZE","Azerbaijan"),
    Country("BA","BIH","Bosnia and Herzegovina"),
    Country("BB","BRB","Barbados"),
    Country("BD","BGD","Bangladesh"),
    Country("BE","BEL","Belgium"),
    Country("BF","BFA","Burkina Faso"),
    Country("BG","BGR","Bulgaria"),
    Country("BH","BHR","Bahrain"),
    Country("BJ","BEN","Benin"),
    Country("BM","BMU","Bermuda"),
    Country("BN","BRN","Brunei Darussalam"),
    Country("BO","BOL","Bolivia, Plurinational State of"),
    Country("BR","BRA","Brazil"),
    Country("BS","BHS","Bahamas"),
    Country("BT","BTN","Bhutan"),
    Country("BW","BWA","Botswana"),
    Country("BY","BLR","Belarus"),
    Country("BZ","BLZ","Belize"),
    Country("CA","CAN","Canada"),
    Country("CD","COD","Congo, The Democratic Republic of the"),
    Country("CF","CAF","Central African Republic (the)"),
    Country("CG","COG","Congo"),
    Country("CH","CHE","Switzerland"),
    Country("CI","CIV","Côte d'Ivoire"),
    Country("CL","CHL","Chile"),
    Country("CM","CMR","Cameroon"),
    Country("CN","CHN","China"),
    Country("CO","COL","Colombia"),
    Country("CR","CRI","Costa Rica"),
    Country("CV","CPV","Cabo Verde"),
    Country("CY","CYP","Cyprus"),
    Country("CZ","CZE","Czechia"),
    Country("DE","DEU","Germany"),
    Country("DK","DNK","Denmark"),
    Country("DM","DMA","Dominica"),
    Country("DO","DOM","Dominican Republic"),
    Country("DZ","DZA","Algeria"),
    Country("EC","ECU","Ecuador"),
    Country("EE","EST","Estonia"),
    Country("EG","EGY","Egypt"),
    Country("ES","ESP","Spain"),
    Country("ET","ETH","Ethiopia"),
    Country("FI","FIN","Finland"),
    Country("FJ","FJI","Fiji"),
    Country("FM","FSM","Micronesia, Federated States of"),
    Country("FR","FRA","France"),
    Country("GA","GAB","Gabon"),
    Country("GB","GBR","United Kingdom"),
    Country("GD","GRD","Grenada"),
    Country("GE","GEO","Georgia"),
    Country("GH","GHA","Ghana"),
    Country("GM","GMB","Gambia"),
    Country("GN","GIN","Guinea"),
    Country("GR","GRC","Greece"),
    Country("GT","GTM","Guatemala"),
    Country("GW","GNB","Guinea-Bissau"),
    Country("GY","GUY","Guyana"),
    Country("HK","HKG","Hong Kong"),
    Country("HN","HND","Honduras"),
    Country("HR","HRV","Croatia"),
    Country("HU","HUN","Hungary"),
    Country("ID","IDN","Indonesia"),
    Country("IE","IRL","Ireland"),
    Country("IL","ISR","Israel"),
    Country("IN","IND","India"),
    Country("IQ","IRQ","Iraq"),
    Country("IS","ISL","Iceland"),
    Country("IT","ITA","Italy"),
    Country("JM","JAM","Jamaica"),
    Country("JO","JOR","Jordan"),
    Country("JP","JPN","Japan"),
    Country("KE","KEN","Kenya"),
    Country("KG","KGZ","Kyrgyzstan"),
    Country("KH","KHM","Cambodia"),
    Country("KN","KNA","Saint Kitts and Nevis"),
    Country("KR","KOR","Korea, Republic of"),
    Country("KW","KWT","Kuwait"),
    Country("KY","CYM","Cayman Islands"),
    Country("KZ","KAZ","Kazakhstan"),
    Country("LA","LAO","Lao People's Democratic Republic"),
    Country("LB","LBN","Lebanon"),
    Country("LC","LCA","Saint Lucia"),
    Country("LI","LIE","Liechtenstein"),
    Country("LK","LKA","Sri Lanka"),
    Country("LR","LBR","Liberia"),
    Country("LT","LTU","Lithuania"),
    Country("LU","LUX","Luxembourg"),
    Country("LV","LVA","Latvia"),
    Country("LY","LBY","Libya"),
    Country("MA","MAR","Morocco"),
    Country("MC","MCO","Monaco"),
    Country("MD","MDA","Moldova, Republic of"),
    Country("ME","MNE","Montenegro"),
    Country("MG","MDG","Madagascar"),
    Country("MK","MKD","North Macedonia"),
    Country("ML","MLI","Mali"),
    Country("MM","MMR","Myanmar"),
    Country("MN","MNG","Mongolia"),
    Country("MO","MAC","Macao"),
    Country("MR","MRT","Mauritania"),
    Country("MS","MSR","Montserrat"),
    Country("MT","MLT","Malta"),
    Country("MU","MUS","Mauritius"),
    Country("MV","MDV","Maldives"),
    Country("MW","MWI","Malawi"),
    Country("MX","MEX","Mexico"),
    Country("MY","MYS","Malaysia"),
    Country("MZ","MOZ","Mozambique"),
    Country("NA","NAM","Namibia"),
    Country("NE","NER","Niger"),
    Country("NG","NGA","Nigeria"),
    Country("NI","NIC","Nicaragua"),
    Country("NL","NLD","Netherlands"),
    Country("NO","NOR","Norway"),
    Country("NP","NPL","Nepal"),
    Country("NR","NRU","Nauru"),
    Country("NZ","NZL","New Zealand"),
    Country("OM","OMN","Oman"),
    Country("PA","PAN","Panama"),
    Country("PE","PER","Peru"),
    Country("PG","PNG","Papua New Guinea"),
    Country("PH","PHL","Philippines"),
    Country("PK","PAK","Pakistan"),
    Country("PL","POL","Poland"),
    Country("PS","PSE","Palestine, State of"),
    Country("PT","PRT","Portugal"),
    Country("PW","PLW","Palau"),
    Country("PY","PRY","Paraguay"),
    Country("QA","QAT","Qatar"),
    Country("RO","ROU","Romania"),
    Country("RS","SRB","Serbia"),
    Country("RU","RUS","Russian Federation"),
    Country("RW","RWA","Rwanda"),
    Country("SA","SAU","Saudi Arabia"),
    Country("SB","SLB","Solomon Islands"),
    Country("SC","SYC","Seychelles"),
    Country("SE","SWE","Sweden"),
    Country("SG","SGP","Singapore"),
    Country("SI","SVN","Slovenia"),
    Country("SK","SVK","Slovakia"),
    Country("SL","SLE","Sierra Leone"),
    Country("SN","SEN","Senegal"),
    Country("SR","SUR","Suriname"),
    Country("ST","STP","Sao Tome and Principe"),
    Country("SV","SLV","El Salvador"),
    Country("SZ","SWZ","Eswatini"),
    Country("TC","TCA","Turks and Caicos Islands"),
    Country("TD","TCD","Chad"),
    Country("TH","THA","Thailand"),
    Country("TJ","TJK","Tajikistan"),
    Country("TM","TKM","Turkmenistan"),
    Country("TN","TUN","Tunisia"),
    Country("TO","TON","Tonga"),
    Country("TR","TUR","Turkey"),
    Country("TT","TTO","Trinidad and Tobago"),
    Country("TW","TWN","Taiwan, Province of China"),
    Country("TZ","TZA","Tanzania, United Republic of"),
    Country("UA","UKR","Ukraine"),
    Country("UG","UGA","Uganda"),
    Country("US","USA","United States"),
    Country("UY","URY","Uruguay"),
    Country("UZ","UZB","Uzbekistan"),
    Country("VC","VCT","Saint Vincent and the Grenadines"),
    Country("VE","VEN","Venezuela, Bolivarian Republic of"),
    Country("VG","VGB","Virgin Islands, British"),
    Country("VN","VNM","Viet Nam"),
    Country("VU","VUT","Vanuatu"),
    Country("WS","WSM","Samoa"),
    Country("XK","XXK","Kosovo"),
    Country("YE","YEM","Yemen"),
    Country("ZA","ZAF","South Africa"),
    Country("ZM","ZMB","Zambia"),
    Country("ZW","ZWE","Zimbabwe")
)

fun getCountryName(alpha:String):String{
    return when(alpha.length){
        2 -> countries.find { it.alpha2 == alpha }?.name?: ""
        3 -> countries.find { it.alpha3 == alpha }?.name?: ""
        else -> ""
    }
}